[package]
edition = "2021"
name = "bevy_2d_gi_experiment"
version = "0.1.0"

[lib]
name = "bevy_2d_gi_experiment"
crate-type = ["cdylib", "lib", "staticlib"]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.68"
bevy = { version = "0.9.1", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_winit", "filesystem_watcher", "png"]}
bevy_egui = { version = "0.18.0", default-features = false }
bevy-inspector-egui = "0.15.0"
egui = { version = "0.20.1", features = ["bytemuck"] }
encase = "0.4.1"
log = "0.4.17"
rand = "0.8.5"

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 3
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
debug = true
incremental = true

[profile.dev]
codegen-units = 16
opt-level = 0
debug = true
incremental = true
